app.config(function($stateProvider,$urlRouterProvider){
    $urlRouterProvider.otherwise('index');
    $stateProvider.state('index',{
      url:'/index',
      templateUrl:'./view/index/content.html'
    }).state('article',{
      url:'/article/?id',
      templateUrl:'./view/article/article.html'
    })
});