app.config(function($stateProvider){
    $stateProvider.state('index',{
      url:'',
      templateUrl:'./view/index/content.html'
    }).state('article',{
      url:'/article/?id',
      templateUrl:'./view/article/article.html'
    })
});